modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
showAsResourcePack=false

[[mods]]
modId="gamblecraft"
version="0.0.1"
displayName="GamebleCraft"
logoFile="logo.png" # this doesnt even exist lol
authors="we love money"
description='''SLOTS! BIG! MONEY!!!'''
displayTest="MATCH_VERSION"

[[dependencies.gamblecraft]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.gamblecraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"